apiVersion: v1
kind: Service
metadata:
  name: springboot-registration-login
  labels:
    app: springboot-registration-login
spec:
  type: NodePort
  selector:
    app: springboot-registration-login
  ports:
    - protocol: TCP
      port: 8010
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-registration-login
spec:
  selector:
    matchLabels:
      app: springbootreg
  replicas: 1
  template:
    metadata:
      labels:
        app: springbootreg
    spec:
      containers:
        - name: springbootreg
          image: jyotidocker/springboot_registration_login
          ports:
            - containerPort: 8010
              livenessProbe:
              httpGet:
                path: /health
                port: 8010
                initialDelaySecond: 30
                timeoutSeconds: 1
